name: Upload git
on:
  workflow_call:
    inputs:
      exec:
        required: false
        type: string
jobs:
  build:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    container: juancolchete/imagemagickgithubactions:latest
    steps:   
      - uses: actions/checkout@v4
      - name: execute actions
        shell: bash
        run: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            ${{ inputs.exec }}
      - name: Upload to git
        id: uploadGit
        shell: bash
        run: |
          curl -s https://raw.githubusercontent.com/juancolchete/utils/main/gitUpload.sh | bash /dev/stdin ${{ vars.GIT_UPLOAD_PARAMS }} "bot: ${{ github.workflow }}"
